### ISSUE TITLE
Documentation for ElasticSearch

### ISSUE THREAD

**Issue by aequasi** [Pipend/pipe#37]
Is there any documentation on how to set this up with elasticsearch

**Comment by furqanZafar** [comment]
the current stable branch is the master branch, just pull in the latest changes & re-install the deps (recent development on the projects branch caused some deps to break, this is fixed in the latest version)
```shell
rm -rf node_modules
npm instal install
```

* click on `new query`
* select the following in the `new query dialog`
```
language: babel
query type: elastic
conn. kind: connection string
conn. string: elastic://your-elastic-cluster.com/index/type
```
here is an example of an elastic query:
the following goes into the query editor:
```javascri[t
{
    query: {
        bool: {
            must: {
                range: {
                    creationTime: {
                        gt: 1466124176307
                    }
                }
            }
        }
    }
}
```

the following goes into transformation editor, this reduces the result of the elastic query to an array of strings (ips in my case):
```
(results) => {
    return results.hits.hits
        .map((result) => result._source)
        .map((_source) => _source.ip)
}
```

the following goes in the presentation editor, this simply displays the json result
```javascript
json
```
